name: 'football_analytics'
version: '1.0.0'
profile: 'football_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  football_analytics:
    staging:
      +materialized: view
      +schema: football_staging
    intermediate:
      +materialized: ephemeral
    core:
      +materialized: table
      +schema: football_core
      scd_club_coach:
        +materialized: incremental
      scd_club_league:
        +materialized: incremental
      scd_player_club:
        +materialized: incremental
      scd_player_market_value:
        +materialized: incremental
    marts:
      +materialized: table
      +schema: football_marts
    ops:
      +materialized: table
      +schema: football_ops
